-- MySQL Script generated by MySQL Workbench
-- seg 19 jun 2023 22:14:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema poli
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema poli
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `poli` DEFAULT CHARACTER SET utf8 ;
USE `poli` ;

-- -----------------------------------------------------
-- Table `poli`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poli`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `img` VARCHAR(45) NOT NULL,
  `ativo` TINYINT NOT NULL DEFAULT 0,
  `description` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poli`.`foto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poli`.`foto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `alt` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `id_categoria` INT NOT NULL,
  `ativo` TINYINT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_foto_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_foto_categoria_idx` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_foto_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `poli`.`categoria` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
